Schema:
  Object Type: "Meta"
  Title: "ASHRAE 205"
  Description: "Base schema for ASHRAE 205 representations"
  Version: "0.2.0"
  References:
    - "ASHRAE205"
    - "RSRESISTANCEWATERHEATSOURCE"
    - "RSCONDENSERWATERHEATSOURCE"

HeatingLogicTemplate:
  Object Type: "Data Group Template"

# Enumerations

HeatSourceType:
  Object Type: "Enumeration"
  Enumerators:
    RESISTANCE:
      Description: "Heat sources that operate by electrical resistance"
      Display Text: "Resistance"
      Notes: ""
    CONDENSER:
      Description: "Heat sources that operate by coolant condenser systems"
      Display Text: "Condenser"
      Notes: ""

HeatingLogicType:
  Object Type: "Enumeration"
  Enumerators:
    STATE_OF_CHARGE_BASED:
      Description: "State-of-charge based"
    TEMPERATURE_BASED:
      Description: "Temperature based"

StandbyTemperatureLocation:
  Object Type: "Enumeration"
  Enumerators:
    TOP_OF_TANK:
      Description: "Refers to top of tank."
      Display Text: "Top of tank"
      Notes: ""
    BOTTOM_OF_TANK:
      Description: "Refers to bottom of tank."
      Display Text: "Bottom of tank"
      Notes: ""

ComparisonType:
  Object Type: "Enumeration"
  Enumerators:
    GREATER_THAN:
      Description: "Decision value is greater than reference value"
      Display Text: "Greater than"
    LESS_THAN:
      Description: "Decision value is less than reference value"
      Display Text: "Less than"

# Data Groups

HeatSourceConfiguration:
  Object Type: "Data Group"
  Data Elements:
    id:
      Description: "Identifier for reference"
      Data Type: "String"
      Required: True
    heat_source_type:
      Description: "Type of heat source"
      Data Type: "<HeatSourceType>"
      Required: True
      Notes: "Determines which heat source data group is used for `heat_source`"
    heat_source:
      Description: "A corresponding Standard 205 heat-source representation"
      Data Type: "({RSRESISTANCEWATERHEATSOURCE},{RSCONDENSERWATERHEATSOURCE})"
      Constraints: "heat_source_type(RESISTANCE, CONDENSER)"
      Required: True
    heat_distribution:
      Description: "Weighted distribution of heat from the heat source along the height of the tank"
      Data Type: "[Numeric]" #"{WeightedDistribution}"
      Required: True
    turn_on_logic:
      Description: "An array of logic conditions that define when the heat source turns on if it is currently off"
      Data Type: "[{HeatingLogic}]"
      Required: True
    shut_off_logic:
      Description: "An array of logic conditions that define when the heat source shuts off if it is currently on"
      Data Type: "[{HeatingLogic}]"
    standby_logic: # TODO: Is this needed?
      Description: "Checks that bottom is below a temperature to prevent short cycling"
      Data Type: "{HeatingLogic}"
      Required: False
    backup_heat_source_id:
      Description: "Reference to the `HeatSourceConfiguration` that engages if this one cannot meet the setpoint"
      Data Type: "String" # TODO: Make an actual reference type (need to use 232 compliant Lattice)
    followed_by_heat_source_id:
      Description: "Reference to the `HeatSourceConfiguration` that should always engage after this one"
      Data Type: "String" # TODO: Make an actual reference type (need to use 232 compliant Lattice)
    companion_heat_source_id:
      Description: "Reference to the `HeatSourceConfiguration` that should always engage concurrently with this one"
      Data Type: "String" # TODO: Make an actual reference type (need to use 232 compliant Lattice)

WeightedDistribution:
  Object Type: "Data Group"
  Data Elements:
    normalized_height:
      Description: "Normalized heights within the tank where the weight is defined between the bottom (0.0), and the top (1.0)"
      Data Type: "[Numeric]"
      Units: "-"
      Constraints: [">=0.0", "<=1.0"]
      Required: True
    weight:
      Description: "Fraction of weight at the corresponding normalized height"
      Data Type: "[Numeric]"
      Units: "-"
      Constraints: [">=0.0", "<=1.0"]
      Required: True

HeatingLogic:
  Object Type: "Data Group"
  Data Elements:
    heating_logic_type:
      Description: "Type of heating logic"
      Data Type: "<HeatingLogicType>"
      Required: True
      Notes: "Determines which heating-logic data group is used for `heating_logic`"
    heating_logic:
      Description: "Specific heating logic"
      Data Type: "({StateOfChargeBasedHeatingLogic},{TemperatureBasedHeatingLogic})"
      Constraints: "heating_logic_type(STATE_OF_CHARGE_BASED, TEMPERATURE_BASED)"
      Required: True
    comparison_type:
      Description: "Result of comparison for activation"
      Data Type: "<ComparisonType>"
      Required: True

TemperatureBasedHeatingLogic:
  Object Type: "Data Group"
  Data Group Template: HeatingLogicTemplate
  Data Elements:
    absolute_temperature:
      Description: "Absolute temperature for activation"
      Data Type: Numeric
      Units: "K"
      Constraints: ">=0.0"
      Required: "if !differential_temperature"
    differential_temperature:
      Description: "Temperature difference for activation"
      Data Type: Numeric
      Units: "K"
      Constraints: ">=0.0"
      Required: "if !absolute_temperature"
    standby_temperature_location:
      Description: "Standby temperature location"
      Data Type: "<StandbyTemperatureLocation>"
      Required: "if !logic_distribution"
    temperature_weight_distribution:
      Description: "Weighted distribution for comparison, by division, in order"
      Data Type: "[Numeric]" #"{WeightedDistribution}"
      Required: True

StateOfChargeBasedHeatingLogic: # This probably needs some re-design to make it meaningful to a manufacturer
  Object Type: "Data Group"
  Data Group Template: HeatingLogicTemplate
  Data Elements:
    decision_point:
      Description: "Decision point"
      Constraints: ">=0.0"
      Data Type: Numeric
      Required: True
    minimum_useful_temperature:
      Description: "Minimum useful temperature"
      Data Type: Numeric
    hysteresis_fraction:
      Description: "Hysteresis fraction"
      Data Type: Numeric
      Units: "-"
      Constraints: [">=0.0", "<=1.0"]
    uses_constant_mains:
      Description: "Uses constant mains"
      Data Type: Boolean
      Required: True
    constant_mains_temperature:
      Description: "Constant mains temperature"
      Constraints: ">=0.0"
      Data Type: Numeric
      Units: "K"
      Required: "if uses_constant_mains"
