name: "Setup Hugo"
description: "Setup Hugo, Pandoc, and Node for Docsy"
inputs:
  os:
    description: Operating system (macos, ubuntu, windows)
    required: true
runs:
  using: composite
  steps:
    - name: Setup Hugo (ubuntu and windows)
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.108.0'
        extended: true
      if: ${{ contains(inputs.os, 'ubuntu') || contains(inputs.os, 'windows') }}
    - name: Setup Hugo (macos)
      run: brew install hugo
      shell: bash
      if: ${{ contains(inputs.os, 'macos') }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.19.2'
