name: "Setup Hugo"
description: "Setup Hugo, Pandoc, and Node for Docsy"
inputs:
  python-version:
    description: Python version used to create the environment
    required: true
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.18"

      # Update Hugo Version in your production platform.
      # Update hugo `version` in `.devcontainer/devcontainer.json` manually.
    - name: Install Hugo
      shell: bash
      run: |
        go install -tags extended github.com/gohugoio/hugo@v0.108.0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.19.2'
