name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Publish
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build and publish package
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
      - name: Build web docs
        run: uv run doit generate_web_docs
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/fan_spec/docs/web/public
